<?php
// Office / instance configuration helpers

function offices_data_directory(): string
{
    return YOJAKA_DATA_PATH . '/offices';
}

function legacy_office_directory(): string
{
    global $config;
    $dir = $config['office_data_path'] ?? (YOJAKA_DATA_PATH . '/office');
    return rtrim($dir, DIRECTORY_SEPARATOR);
}

function legacy_office_config_path(): string
{
    global $config;
    $file = $config['office_config_file'] ?? 'office.json';
    return legacy_office_directory() . DIRECTORY_SEPARATOR . $file;
}

function offices_registry_path(): string
{
    return offices_data_directory() . DIRECTORY_SEPARATOR . 'offices.json';
}

function office_config_path_by_file(string $file): string
{
    return offices_data_directory() . DIRECTORY_SEPARATOR . $file;
}

function default_print_config(array $officeDefaults = []): array
{
    $officeName = $officeDefaults['office_name'] ?? 'Yojaka Office';
    $officeAddress = $officeDefaults['office_address'] ?? 'Add office address here';

    return [
        'page_size' => 'A4',
        'show_header' => true,
        'show_footer' => true,
        'header_html' => '<h2>' . htmlspecialchars($officeName, ENT_QUOTES) . '</h2><div>' . htmlspecialchars($officeAddress, ENT_QUOTES) . '</div>',
        'footer_html' => '<p>Generated by Yojaka</p>',
        'logo_path' => '',
        'watermark_text' => 'TRIAL COPY - NOT FOR PRODUCTION',
        'watermark_enabled' => false,
    ];
}

function default_office_config(): array
{
    return [
        'office_name' => 'Yojaka Office',
        'office_short_name' => 'YOJAKA',
        'base_url' => YOJAKA_BASE_URL,
        'date_format_php' => 'd-m-Y',
        'timezone' => 'Asia/Kolkata',
        'default_language' => 'en',
        'id_prefixes' => [
            'rti' => 'RTI',
            'dak' => 'DAK',
            'inspection' => 'INSP',
            'bill' => 'BILL',
            'meeting_minutes' => 'MM',
            'work_order' => 'WO',
            'guc' => 'GUC',
        ],
        'theme' => [
            'primary_color' => '#0f5aa5',
            'secondary_color' => '#f5f7fb',
            'logo_path' => '',
        ],
        'modules' => [
            'enable_rti' => true,
            'enable_dak' => true,
            'enable_inspection' => true,
            'enable_bills' => true,
            'enable_meeting_minutes' => true,
            'enable_work_orders' => true,
            'enable_guc' => true,
        ],
        'custom_fields' => [
            'rti' => [],
            'dak' => [],
            'bills' => [],
            'documents' => [],
        ],
        'ui' => [
            'menus' => new stdClass(),
            'dashboard_widgets' => function_exists('default_dashboard_widgets') ? default_dashboard_widgets() : [],
        ],
        'portal' => [
            'enabled' => false,
            'features' => [
                'rti_status' => true,
                'dak_status' => true,
                'request' => true,
            ],
            'kiosk' => [
                'enabled' => false,
                'default_action' => '',
                'idle_timeout_seconds' => 300,
            ],
        ],
        'print' => default_print_config(['office_name' => 'Yojaka Office']),
    ];
}

function ensure_office_storage(): void
{
    $dir = offices_data_directory();
    if (!is_dir($dir)) {
        @mkdir($dir, 0755, true);
    }
    $htaccess = $dir . DIRECTORY_SEPARATOR . '.htaccess';
    if (!file_exists($htaccess)) {
        @file_put_contents($htaccess, "Deny from all\n<IfModule mod_autoindex.c>\n  Options -Indexes\n</IfModule>\n");
    }
}

function seed_default_office_files(): void
{
    ensure_office_storage();

    $dir = offices_data_directory();
    $officeId = 'office_001';
    $registryPath = offices_registry_path();
    $officeConfigPath = $dir . DIRECTORY_SEPARATOR . $officeId . '.json';
    $licensePath = $dir . DIRECTORY_SEPARATOR . 'license_' . $officeId . '.json';

    if (!file_exists($registryPath)) {
        $baseConfig = default_office_config();
        $registry = [[
            'id' => $officeId,
            'name' => $baseConfig['office_name'] ?? 'Default Office',
            'short_name' => $baseConfig['office_short_name'] ?? 'YOJAKA',
            'active' => true,
            'config_file' => basename($officeConfigPath),
            'license_file' => basename($licensePath),
            'created_at' => gmdate('c'),
        ]];
        @file_put_contents($registryPath, json_encode($registry, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }

    if (!file_exists($officeConfigPath)) {
        $baseConfig = default_office_config();
        @file_put_contents($officeConfigPath, json_encode($baseConfig, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }

    if (!file_exists($licensePath)) {
        $officeConfig = json_decode((string) @file_get_contents($officeConfigPath), true);
        $officeName = is_array($officeConfig) ? ($officeConfig['office_name'] ?? $officeId) : $officeId;
        $license = function_exists('default_trial_license') ? default_trial_license($officeId, $officeName) : [
            'license_key' => 'YOJAKA-TRIAL-' . strtoupper(substr(md5($officeId), 0, 6)),
            'licensed_to' => $officeName,
            'office_id' => $officeId,
            'issue_date' => date('Y-m-d'),
            'expiry_date' => date('Y-m-d', strtotime('+30 days')),
            'type' => 'trial',
        ];
        @file_put_contents($licensePath, json_encode($license, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }
}

function load_offices_registry(): array
{
    ensure_office_storage();
    $registryPath = offices_registry_path();
    if (!file_exists($registryPath)) {
        seed_default_office_files();
    }

    if (!file_exists($registryPath)) {
        return [];
    }

    $data = json_decode((string) file_get_contents($registryPath), true);
    return is_array($data) ? $data : [];
}

function save_offices_registry(array $offices): void
{
    $path = offices_registry_path();
    $handle = fopen($path, 'c+');
    if (!$handle) {
        return;
    }
    if (flock($handle, LOCK_EX)) {
        ftruncate($handle, 0);
        rewind($handle);
        fwrite($handle, json_encode(array_values($offices), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        fflush($handle);
        flock($handle, LOCK_UN);
    }
    fclose($handle);
}

function save_office_config_by_id(string $officeId, string $configFile, array $office): bool
{
    ensure_office_storage();
    $path = office_config_path_by_file($configFile);
    $handle = @fopen($path, 'c+');
    if (!$handle) {
        return false;
    }
    if (flock($handle, LOCK_EX)) {
        ftruncate($handle, 0);
        rewind($handle);
        fwrite($handle, json_encode($office, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        fflush($handle);
        flock($handle, LOCK_UN);
    }
    fclose($handle);
    return true;
}

function save_office_config(string $officeId, array $config): bool
{
    ensure_office_storage();
    $dir = offices_data_directory();
    $file = $dir . DIRECTORY_SEPARATOR . $officeId . '.json';
    $config['id'] = $officeId;

    $handle = @fopen($file, 'c+');
    if (!$handle) {
        return false;
    }

    $result = false;
    if (flock($handle, LOCK_EX)) {
        ftruncate($handle, 0);
        rewind($handle);
        $result = fwrite($handle, json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)) !== false;
        fflush($handle);
        flock($handle, LOCK_UN);
    }
    fclose($handle);
    return $result;
}

function load_office_config_by_id(string $officeId): array
{
    $registry = load_offices_registry();
    foreach ($registry as $office) {
        if (($office['id'] ?? '') === $officeId) {
            $path = office_config_path_by_file($office['config_file'] ?? ($officeId . '.json'));
            if (!file_exists($path)) {
                save_office_config_by_id($officeId, $office['config_file'] ?? ($officeId . '.json'), default_office_config());
            }
            $data = json_decode((string) file_get_contents($path), true);
            return is_array($data) ? array_replace_recursive(default_office_config(), $data) : default_office_config();
        }
    }
    return default_office_config();
}

function load_office_config(): array
{
    // Department is now the larger unit (legacy "office" scope). We keep the
    // physical directory naming for backward compatibility but clarify the
    // meaning here so other helpers can map appropriately.
    return load_office_config_by_id(get_current_department_id());
}

function office_print_config(string $officeId): array
{
    $office = load_office_config_by_id($officeId);
    $defaults = default_print_config($office);
    $custom = $office['print'] ?? [];
    $print = is_array($custom) ? array_replace_recursive($defaults, $custom) : $defaults;

    $pageSize = strtoupper($print['page_size'] ?? 'A4');
    if (!in_array($pageSize, ['A4', 'LETTER'], true)) {
        $pageSize = 'A4';
    }
    $print['page_size'] = $pageSize;

    return $print;
}

function get_id_prefix(string $type, string $fallback = ''): string
{
    $office = load_office_config();
    return $office['id_prefixes'][$type] ?? ($fallback !== '' ? $fallback : strtoupper($type));
}

function format_date_for_display(?string $dateString): string
{
    if (!$dateString) {
        return '';
    }
    $office = load_office_config();
    $format = $office['date_format_php'] ?? 'd-m-Y';
    $timezone = $office['timezone'] ?? date_default_timezone_get();
    try {
        $date = new DateTime($dateString, new DateTimeZone($timezone));
        return $date->format($format);
    } catch (Throwable $e) {
        return $dateString;
    }
}

function is_module_enabled(string $moduleKey): bool
{
    $office = load_office_config();
    $flagKey = 'enable_' . $moduleKey;
    return !empty($office['modules'][$flagKey]);
}

function require_module_enabled(string $moduleKey): void
{
    if (!is_module_enabled($moduleKey)) {
        echo '<div class="alert alert-danger">This module is disabled for this office instance.</div>';
        exit;
    }
}

function get_default_office_id(): string
{
    $registry = load_offices_registry();
    if (!empty($registry)) {
        return $registry[0]['id'] ?? 'office_001';
    }
    return 'office_001';
}

function get_current_department_id(): string
{
    // Department (big unit) maps to the legacy office identifier used for
    // folder naming. We preserve the stored value but clarify semantics.
    if (!empty($GLOBALS['current_department_id_override'])) {
        return $GLOBALS['current_department_id_override'];
    }
    $user = current_user();
    if ($user && !empty($user['office_id'])) {
        return $user['office_id'];
    }
    return get_default_office_id();
}

function get_current_office_id(): string
{
    // Office (smaller unit within a department) now maps to what was
    // previously stored as department_id. We fall back to the department id to
    // remain compatible with older data where no inner office was captured.
    if (!empty($GLOBALS['current_office_id_override'])) {
        return $GLOBALS['current_office_id_override'];
    }
    $user = current_user();
    if ($user && !empty($user['department_id'])) {
        return $user['department_id'];
    }
    if ($user && !empty($user['office_id'])) {
        return $user['office_id'];
    }
    return get_default_office_id();
}

function filter_records_by_office(array $records, string $officeId): array
{
    return array_values(array_filter($records, function ($item) use ($officeId) {
        return ($item['office_id'] ?? $officeId) === $officeId;
    }));
}

function ensure_record_office(array $record, string $officeId): array
{
    if (empty($record['office_id'])) {
        $record['office_id'] = $officeId;
    }
    return $record;
}

function get_current_office_config(): array
{
    return $GLOBALS['current_office_config'] ?? load_office_config_by_id(get_current_department_id());
}

function find_office_registry_entry(string $officeId): ?array
{
    $registry = load_offices_registry();
    foreach ($registry as $office) {
        if (($office['id'] ?? '') === $officeId) {
            return $office;
        }
    }
    return null;
}


?>
